# Numpy와 pandas로 데이터 분석하기
- ### 데이터 분석을 위한 Python 라이브러리 3 종
    - Numpy
    - Pandas

- ### Pandas 를 활용한 데이터 분석
- ### 데이터 분석을 위한 Python 라이브러리 3가지!
    ①  Matplotlib<br>
    ②  Numpy<br>
    ③  Pandas<br>
- ### 테이블 모양 데이터 다루기
![ex01](https://github.com/KimTaesong/intelligence-and-information-system/blob/master/Week5/img/ex01.PNG)

- ### 데이터 분석을 위한 Python 라이브러리 3가지!
    ①  <b>Matplotlib</b> -> (확장) -> seaborn<br>
    -더 알고 실다면! https://matplotlib.org/gallery.html<br>
    ②  Numpy<br>
    ③  Pandas<br>
- ### 테이블 모양 데이터 다루기
![ex01](.\img\ex01.png)

- ### 데이터 분석을 위한 Python 라이브러리 3가지!
    ①  Matplotlib<br>
    ②  <b>Numpy</b><br>
    - Numerical 의 줄임말
    - 행렬 , 수치 계산 등 데이터를 다루기 쉽게 도와줌
        - 고성능의 과학 계산 컴퓨팅과 데이터 분석에 필요한 라이브러리
    - 튜토리얼 : https://numpy.org/devdocs/user/quickstart.html<br>
  
  
  
  
   |항목1|항목2|항목3|항목4| 
   |--|--|--|--|
   |14|0|0|2|
   |13|5|4|8|
   |24|21|25|28|
  
    ③  Pandas
  
   



- ### 데이터 분석을 위한 Python 라이브러리 3가지!
    ①  Matplotlib<br>
    ②  Numpy<br>
    ③  <b>Pandas</b><br>
    - Panel Datas 의 줄임말
    - 테이블 형태의 데이터를 다루게 쉽게 도와주는 라이브러리
    - csv, html, sql 등 다양한 데이터를 읽을 수 있음
    - 튜토리얼 : https://pandas.pydata.org/pandas
docs/stable/getting_started/intro_tutorials/index.html

|나라|참가횟수|금|은|동|
|:---:|:---:|:---:|:---:|:---:|
|아프가니스탄|14|0|0|2|
|알제니|13|5|5|8|
|아르헨티나|24|21|25|28|

![ex01](./img/ex01.png)

## Numpy란?
- ### numpy 는 수치 데이터를 다루기 위한 라이브러리
    - (다차원 배열 구조인 ndarray 를 이용하여) 행렬 벡터 및 수치 연산을 빠르게 하는 것이 핵심

    - list 와 numpy array 의 연산 속도 차이는 30~40 배까지 나기도 함
        - C 언어로 구현된 파이썬 라이브러리
- ### 데이터의 크기가 커질수록 numpy 는 필수
- ### numpy 의 array( 배열) 에 대해 알아보겠습니다
    - ### import numpy as np

## 차원(Dimesion)
- ### 중첩 리스트
- ### 리스트 안의 리스트
- 차원 ? 중첩된 정도를 구분하기 위한 단위
    - Ex. 1 번 중첩되면 1 차원 , 2 번 중첩되면 2 차원
- ### 일반적인 리스트는 중첩 데이터를 처리하는 게 느리고 복잡 -> numpy 라이브러리 사용


In [13]:
[1,2,3,4]                            # 1차원
[[1,2,3,4],[5,6,7,8]]                # 2차원
[[[1,2,3,4],[5,6,7,8]],[[1,3,4,5]]]  # 3차원

[[[1, 2, 3, 4], [5, 6, 7, 8]], [[1, 3, 4, 5]]]

## np.array()
- ### Numpy 의 핵심은 ndarray
    - np.array 는 리스트 , 튜플 , 배열로 부터 ndarray 를 생성
- ### 리스트(list)로 1차원 배열을 생성해보기

In [14]:
# numpy 라이브러리 import 하기
import numpy as np
# 1차원 배열 생성하기
a = np.array([1,2,3,4,5])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3 4 5]


- ### 2차원 배열 생성해보기
    - 리스트의 리스트를 입력 값으로 !

In [15]:
# 2차원 배열 생성하기
b = np.array([[1,2,3],[4,5,6]])
print(type(b))
print(b)


<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]


In [16]:
# 변수를 사용하여 2차원 배열 생성하기
i_list = [[1,2,3],[4,5,6]]
b = np.array(i_list)
print(type(b))
print(b)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]


- ### 배열의 차원 및 크기 확인
    - ndim 및 shape 속성으로 출력하기

In [17]:
# 배열의 차원 및 크기 확인
# ndim 및 shape 속성으로 출력하기
print(b.ndim)
print(b.shape)

2
(2, 3)


2차원이며, 2 x 3 크기의 배열

In [18]:
print(a.ndim)
print(a.shape)

1
(5,)


1차원이며, 크기 5의 배열