# Numpy란
   - ## 1.ndarray 초기화 방법들
   - ## 2.슬라이싱 (Slicing)
   - ## 3.Numpy 연산
   - ## 4.Numpy array 와 list 의 차이


## 1. ndarray 초기화 방법들
- ### 리스트를 이용하여 ndarray 를 생성하기
- ### 그 외에 ndarray 를 만드는 다양한 방법
    - np.zeros((a,b))
    - np.ones ((a, b))
    - np.full ((a, b),c)
    - np.eye (a)
    - np.random.random (a,b)
    – ...<br>
    
데이터 분석에서는 분석의 대상이 되는 데이터가 이미 존재 -> 초기화를 사용할 일은 거의 없음
그러나 numpy 의 특징을 살펴보기 위해

## ndarray 초기화
### 리스트를 이용하여 ndarray 를 생성하기
### 그 외에 ndarray 를 만드는 다양한 방법
- <b>np.zeros (shape=(a,b)) 혹은 np.zeros((a,b))</b>
    - 모든 값이 0 인 a x b 크기의 배열 생성
    - numpy.zeros (shape, dtype =float, order=‘C')
        - https://numpy.org/doc/stable/reference/generated/numpy.zeros.html

![ex02](./img/ex02.png)

In [33]:
import numpy as np
#  모든 값이 0인 2x3인 배열 생성
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

- <b>np.ones (shape=(a, b)) 혹은 np.ones ((a,b))</b>
    - 모든 값이 1 인 a x b 크기의 배열 생성
    - numpy.ones (shape, dtype =None, order='
        - https://numpy.org/doc/stable/reference/generated/numpy.ones.html

In [34]:
# 모든 값이 1인 2x3 배열 생성
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

- <b>np.full (shape=(a, b), fill_value =c) 혹은 np.full ((a, b),c)</b>
    - 모든 값이 c 인 a x b 크기의 배열 생성
    - numpy.full (shape, fill_value , dtype =None, order='C')
        - https://numpy.org/doc/stable/reference/generated/numpy.full.html

In [35]:
# 모든 값이 5인 2 x 3 배열 생성
a = np.full((2,3),5)
a

array([[5, 5, 5],
       [5, 5, 5]])

In [36]:
#dtype 설정하기: np int8
b = np.full((2,3),5, dtype =np.int8)
b

array([[5, 5, 5],
       [5, 5, 5]], dtype=int8)

In [37]:
#dtype 설정하기: np float64
b = np.full((2,3),5, dtype =np.float64)
b

array([[5., 5., 5.],
       [5., 5., 5.]])

In [38]:
# 모든 값이 1.5 인 2x3 배열 생성
d = np.full((2,3),1.5)
d

array([[1.5, 1.5, 1.5],
       [1.5, 1.5, 1.5]])

- <b>np.eye(a)</b>
    - 대각선 값은 1 이고 나머지는 0 인 a x a 크기의 2 차원 배열 생성
    - 만약 np.eye (a, 인 경우 a x b 크기의 2 차원 배열 생성
    - numpy.eye (N, M=None, k=0, dtype =<class 'float'>, order='C')
        - https://numpy.org/doc/stable/reference/generated/numpy.eye.html

In [39]:
# 대각선 값은 1이고 나머지는 0인 a x a 크기의 2차원 배열 생성
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
# 대각선 값은 1이고 나머지는 0인 axb 크기의 2차원 배열 생성
a = np.eye(3,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

- <b>np.random.randn(a,b)</b>
    - 임의의 값으로 채워진 a x b 크기의 배열 생성
    - numpy.random.randn (d0, d1, ..., dn)
        - 
https://numpy.org/doc/stable/reference/random/generated/numpy.random.randn.html

In [41]:
# 임의의 값으로 채워진 a x b 크기의 배열 생성
np.random.randn(2,3)

array([[ 0.69713413,  2.22251508, -0.78789743],
       [ 0.03243042,  0.71131201, -0.92061461]])

## 2. 슬라이싱
- ### 슬라이싱(Slicing)
   -  ndarray 를 통해 만든 다차원 배열은 list 처럼 슬라이스 (Slice) 기능을 지원
       - 슬라이스 기능을 사용하여 여러 개의 원소에 접근할 수 있음
   - 각 차원 별로 슬라이스 범위를 지정해줘야 함

In [42]:
a = np.array([1,2,3])
b = a[0:2]
b

array([1, 2])

In [43]:
a = np.array([[1,2,3],[4,5,6]])
b = a[0:2, 0:2]
b

array([[1, 2],
       [4, 5]])

## 3. Numpy 연산
- ### ndarray 로 만든 자료형은 자유롭게 사칙연산이 가능
    - 배열 간 연산을 손쉽게 수행할 수 있음
        -  +, - , * , /  의 연산자 사용
        - add(), substract (), multiply(), divide() 함수 사용


In [44]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [45]:
# 동일한 인덱스에 위치한 요소끼리 덧셈
# c = np.add(a,b)와 동일
c = a + b
c

array([5, 7, 9])

In [46]:
# 동일한 인덱스에 위치한 요소끼리 뺄셈
# c = np.substract(a,b)와 동일
c = a - b
c

array([-3, -3, -3])

In [47]:
#동일한 인덱스에 위치한 요소끼리 곱셈
c = a * b
c

array([ 4, 10, 18])

In [48]:
#동일한 인덱스에 위치한 요소끼리 나눗셈
# c = np.divide(a,b)와 동일
c = a / b
c

array([0.25, 0.4 , 0.5 ])

## 4. Numpy array 와 list 의 차이
- ### 사칙연산
    - numpy array 는 numpy array 끼리 사칙연산이 가능하지만 Python list 는 <b>덧셈</b> 만 가능
    -----
    - numpy array + numpy array
        - 같은 인덱스에 있는 값들끼리 더해짐

        - Ex.[1, 2, 3, 4, 5] + [1, 3, 5, 7, 9] →[2, 5, 8, 11, 14]
    - list + list
        - 두 리스트의 값들이 한 리스트로 합쳐짐 (concatenation)
        - Ex.[1, 2, 3, 4, 5] + [1, 3, 5, 7, 9] →[1, 2, 3, 4, 5, 1, 3, 5, 7, 9]
       
    -----
    - numpy array 는 numpy array 끼리 <b>뺄셈 , 곱셈 , 나눗셈</b> 가능
        - 같은 인덱스에 있는 값들끼리 연산
    - Python list 는 list 끼리 뺄셈 , 곱셈 , 나눗셈을 하면 <b>오류</b> 발생

### Numpy array 는 array 전체에 연산 이 가능하지만 Python list 는 곱셈 만 가능
- numpy array 와 숫자의 연산 -> array 에 들어있는 각 값에 연산이 적용됨(+, -, *, / 모두 가능)
    - numpy array + 5
        - array 안에 들어있는 각 값에 +5
        - Ex. [1, 2, 3] + 5 →[6, 7, 8]
- Python list 는 곱셈만 가능
    - array 처럼 각 값에 곱을 해주는 것이 아닌 , list 의 요소를 해당숫자만큼 반복!
        - Ex. [1, 2, 3] * 3 →[1, 2, 3, 1, 2, 3, 1, 2, 3]

### 성능 차이
- Python list 에 비해 문법이 간단하고 성능이 뛰어남
    - 예를 들어 1 억 개의 요소가 있는 기본 python list 에 곱하기 2 를 하려면?
        - 반복문을 1 억 번 돌려야 함
        - numpy array 는 그냥 * 2 만 붙여주면 됨
- 성능 차이가 나는 이유
    - 값들이 저장되는 방식에 차이
        - python list 는 다양한 자료형을 저장 가능
        - numpy array 는 같은 자료형만 저장 가능
        
### 결론
- python list -> 값을 추가하고 제거할 때 사용
- numpy array -> 수치 계산이 많고 복잡할 때 혹은 행렬 같은
다차원 배열을 쓸 때 사용
